INSERT INTO marque (id, nom)
VALUES
    (UUID(), 'Alpine'),
    (UUID(), 'Bugatti'),
    (UUID(), 'Peugeot'),
    (UUID(), 'Citroën'),
    (UUID(), 'Renault'),
    (UUID(), 'Tesla'),
    (UUID(), 'BMW'),
    (UUID(), 'Mercedes-Benz'),
    (UUID(), 'Audi'),
    (UUID(), 'Porsche'),
    (UUID(), 'Ferrari'),
    (UUID(), 'Lamborghini'),
    (UUID(), 'Maserati'),
    (UUID(), 'Aston Martin'),
    (UUID(), 'Jaguar'),
    (UUID(), 'Land Rover'),
    (UUID(), 'Ford'),
    (UUID(), 'Chevrolet'),
    (UUID(), 'Honda'),
    (UUID(), 'Toyota');

INSERT INTO modele_voiture (id, nom, nb_place, description, marque_id)
VALUES
    (UUID(), 'Alpine A110', 2, 'Coupé sportif français au design élégant et aux performances dynamiques.', (SELECT id FROM marque WHERE nom = 'Alpine')),
    (UUID(), 'Bugatti Chiron', 2, 'Hypercar luxueuse et puissante, célèbre pour sa vitesse record et son style exclusif.', (SELECT id FROM marque WHERE nom = 'Bugatti')),
    (UUID(), 'Peugeot 3008', 5, 'SUV familial spacieux avec un design moderne et une technologie de pointe.', (SELECT id FROM marque WHERE nom = 'Peugeot')),
    (UUID(), 'Citroën C4', 5, 'Compacte confortable avec un design unique et une conduite souple.', (SELECT id FROM marque WHERE nom = 'Citroën')),
    (UUID(), 'Renault Clio', 5, 'Polyvalente et économique, idéale pour la ville avec une touche de sportivité.', (SELECT id FROM marque WHERE nom = 'Renault')),
    (UUID(), 'Tesla Model S', 5, 'Berline électrique haut de gamme avec une autonomie impressionnante et des performances accrues.', (SELECT id FROM marque WHERE nom = 'Tesla')),
    (UUID(), 'BMW X5', 5, 'SUV de luxe offrant confort, puissance et technologie de pointe.', (SELECT id FROM marque WHERE nom = 'BMW')),
    (UUID(), 'Mercedes-Benz Classe C', 5, 'Berline élégante avec des finitions premium et une conduite raffinée.', (SELECT id FROM marque WHERE nom = 'Mercedes-Benz')),
    (UUID(), 'Audi Q7', 7, 'SUV familial spacieux et puissant, parfait pour les longs trajets.', (SELECT id FROM marque WHERE nom = 'Audi')),
    (UUID(), 'Porsche 911', 4, 'Icône du design sportif avec des performances exceptionnelles et un charme intemporel.', (SELECT id FROM marque WHERE nom = 'Porsche')),
    (UUID(), 'Ferrari 488', 2, 'Supercar italienne légendaire avec des performances élevées et un style incomparable.', (SELECT id FROM marque WHERE nom = 'Ferrari')),
    (UUID(), 'Lamborghini Huracán', 2, 'Voiture de sport à couper le souffle avec une puissance brute et un look audacieux.', (SELECT id FROM marque WHERE nom = 'Lamborghini')),
    (UUID(), 'Maserati Levante', 5, 'SUV luxueux combinant élégance italienne et puissance pour tous les terrains.', (SELECT id FROM marque WHERE nom = 'Maserati')),
    (UUID(), 'Aston Martin DB11', 4, 'GT britannique élégante, synonyme de sophistication et de performance.', (SELECT id FROM marque WHERE nom = 'Aston Martin')),
    (UUID(), 'Jaguar F-PACE', 5, 'SUV alliant luxe, performance et un design audacieux signé Jaguar.', (SELECT id FROM marque WHERE nom = 'Jaguar')),
    (UUID(), 'Land Rover Range Rover', 5, 'SUV emblématique offrant un luxe inégalé et des capacités tout-terrain.', (SELECT id FROM marque WHERE nom = 'Land Rover')),
    (UUID(), 'Ford Mustang', 4, 'Muscle car américaine iconique, symbolisant la puissance et la liberté.', (SELECT id FROM marque WHERE nom = 'Ford')),
    (UUID(), 'Chevrolet Camaro', 4, 'Voiture de sport musclée au design captivant et aux performances envoûtantes.', (SELECT id FROM marque WHERE nom = 'Chevrolet')),
    (UUID(), 'Honda Civic', 5, 'Compacte fiable et économique, dotée de technologies avancées.', (SELECT id FROM marque WHERE nom = 'Honda')),
    (UUID(), 'Toyota Prius', 5, 'Hybride pionnière alliant économie de carburant et technologie écologique.', (SELECT id FROM marque WHERE nom = 'Toyota'));

INSERT INTO pays (id, nom)
VALUES
    (UUID(), 'France'),
    (UUID(), 'Germany'),
    (UUID(), 'Italy'),
    (UUID(), 'Spain'),
    (UUID(), 'Portugal'),
    (UUID(), 'Belgium'),
    (UUID(), 'Netherlands'),
    (UUID(), 'Switzerland'),
    (UUID(), 'Austria'),
    (UUID(), 'United Kingdom'),
    (UUID(), 'United States'),
    (UUID(), 'Canada'),
    (UUID(), 'Mexico'),
    (UUID(), 'Brazil'),
    (UUID(), 'Argentina'),
    (UUID(), 'Japan'),
    (UUID(), 'South Korea'),
    (UUID(), 'China'),
    (UUID(), 'Australia'),
    (UUID(), 'India');

INSERT INTO ville (id, nom, pays_id)
VALUES
    (UUID(), 'Bonchamp', (SELECT id FROM pays WHERE nom = 'France')),
    (UUID(), 'Paris', (SELECT id FROM pays WHERE nom = 'France')),
    (UUID(), 'Lyon', (SELECT id FROM pays WHERE nom = 'France')),
    (UUID(), 'Berlin', (SELECT id FROM pays WHERE nom = 'Germany')),
    (UUID(), 'Munich', (SELECT id FROM pays WHERE nom = 'Germany')),
    (UUID(), 'Rome', (SELECT id FROM pays WHERE nom = 'Italy')),
    (UUID(), 'Milan', (SELECT id FROM pays WHERE nom = 'Italy')),
    (UUID(), 'Madrid', (SELECT id FROM pays WHERE nom = 'Spain')),
    (UUID(), 'Barcelona', (SELECT id FROM pays WHERE nom = 'Spain')),
    (UUID(), 'Lisbon', (SELECT id FROM pays WHERE nom = 'Portugal')),
    (UUID(), 'Brussels', (SELECT id FROM pays WHERE nom = 'Belgium')),
    (UUID(), 'Amsterdam', (SELECT id FROM pays WHERE nom = 'Netherlands')),
    (UUID(), 'Zurich', (SELECT id FROM pays WHERE nom = 'Switzerland')),
    (UUID(), 'Geneva', (SELECT id FROM pays WHERE nom = 'Switzerland')),
    (UUID(), 'Vienna', (SELECT id FROM pays WHERE nom = 'Austria')),
    (UUID(), 'London', (SELECT id FROM pays WHERE nom = 'United Kingdom')),
    (UUID(), 'New York', (SELECT id FROM pays WHERE nom = 'United States')),
    (UUID(), 'Los Angeles', (SELECT id FROM pays WHERE nom = 'United States')),
    (UUID(), 'Toronto', (SELECT id FROM pays WHERE nom = 'Canada')),
    (UUID(), 'Mexico City', (SELECT id FROM pays WHERE nom = 'Mexico'));

INSERT INTO voiture (id, prix, modele_id, ville_id)
VALUES
    (UUID(), 150, (SELECT id FROM modele_voiture WHERE nom = 'Alpine A110'), (SELECT id FROM ville WHERE nom = 'Paris')),
    (UUID(), 1200, (SELECT id FROM modele_voiture WHERE nom = 'Bugatti Chiron'), (SELECT id FROM ville WHERE nom = 'Lyon')),
    (UUID(), 100, (SELECT id FROM modele_voiture WHERE nom = 'Peugeot 3008'), (SELECT id FROM ville WHERE nom = 'Berlin')),
    (UUID(), 90, (SELECT id FROM modele_voiture WHERE nom = 'Citroën C4'), (SELECT id FROM ville WHERE nom = 'Munich')),
    (UUID(), 60, (SELECT id FROM modele_voiture WHERE nom = 'Renault Clio'), (SELECT id FROM ville WHERE nom = 'Rome')),
    (UUID(), 250, (SELECT id FROM modele_voiture WHERE nom = 'Tesla Model S'), (SELECT id FROM ville WHERE nom = 'Milan')),
    (UUID(), 220, (SELECT id FROM modele_voiture WHERE nom = 'BMW X5'), (SELECT id FROM ville WHERE nom = 'Madrid')),
    (UUID(), 200, (SELECT id FROM modele_voiture WHERE nom = 'Mercedes-Benz Classe C'), (SELECT id FROM ville WHERE nom = 'Barcelona')),
    (UUID(), 180, (SELECT id FROM modele_voiture WHERE nom = 'Audi Q7'), (SELECT id FROM ville WHERE nom = 'Lisbon')),
    (UUID(), 500, (SELECT id FROM modele_voiture WHERE nom = 'Porsche 911'), (SELECT id FROM ville WHERE nom = 'Brussels')),
    (UUID(), 800, (SELECT id FROM modele_voiture WHERE nom = 'Ferrari 488'), (SELECT id FROM ville WHERE nom = 'Amsterdam')),
    (UUID(), 750, (SELECT id FROM modele_voiture WHERE nom = 'Lamborghini Huracán'), (SELECT id FROM ville WHERE nom = 'Zurich'));
